import type { ChatImageAttachment } from "./image-chat.js";
export const characters = [
  {
    id: "lin",
    name: "林野",
    kind: "虚拟角色",
    emoji: "🌿",
    color: "sage",
    role: "散步搭子",
    description: "慢一点，也能发现有趣的事。",
    greeting: "刚沿着河边走了一圈，风很舒服。你今天过得怎么样？",
    starters: ["今天有点累", "一起想个周末计划"],
  },
  {
    id: "tao",
    name: "陶陶",
    kind: "虚拟角色",
    emoji: "🍊",
    color: "peach",
    role: "灵感好友",
    description: "一杯果茶，一点天马行空。",
    greeting: "我刚想给今天起个名字，暂定「橘子汽水日」。你的今天叫什么？",
    starters: ["给我一个小小的创意", "今天发生了件好事"],
  },
  {
    id: "dou",
    name: "豆包",
    kind: "虚拟宠物",
    emoji: "🐕",
    color: "sand",
    role: "小狗伙伴",
    description: "尾巴摇一摇，快乐很简单。",
    greeting: "汪！我给你留了草地上最舒服的位置。今天想聊什么呀？",
    starters: ["豆包，陪我放松一下", "你今天玩了什么？"],
  },
  {
    id: "moon",
    name: "月饼",
    kind: "虚拟宠物",
    emoji: "🐈",
    color: "lavender",
    role: "窗边小猫",
    description: "晒晒太阳，听你慢慢说。",
    greeting: "喵，窗边的太阳刚刚好。你可以坐一会儿，想说什么都可以。",
    starters: ["想安静待一会儿", "跟我讲个小故事"],
  },
] as const;
export type BuiltinId = (typeof characters)[number]["id"];
export type CharacterId = string;
export type Character = {
  id: string;
  // Generated by local avatar storage, never copied from character-card JSON.
  avatarUrl?: string;
  name: string;
  kind: string;
  emoji: string;
  color: string;
  role: string;
  description: string;
  greeting: string;
  starters: readonly string[];
};
export type Mode = "demo" | "live";
export type Message = {
  id: string;
  role: "user" | "assistant";
  content: string;
  mode?: Mode;
  image?: ChatImageAttachment;
};
// imageOmitted is a request-only marker; never replace the stored image reference.
export type ChatMessage = Pick<Message, "role" | "content" | "image"> & { imageOmitted?: true };
export type ChatRequest = {
  characterId: CharacterId;
  messages: ChatMessage[];
};
export const MAX_MESSAGE_LENGTH = 2000;
export const MAX_HISTORY = 40;
export function getCharacter(id: string) {
  return characters.find((character) => character.id === id);
}
